fix: Add delete supplement note functionality
bcgov/nr-compliance-enforcement pull request #339
Opened 2024-04-15 17:55 UTC by marqueone-ps

# Description
Adds the ability to remove a note from a case file

Bug # CE-601

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Manual testing?

2024-04-17 00:55 UTC, Scarlett-Truong requested changes
There's a bug I encountered: when you started create a Note first, without create other Outcome like Assessment or Prevention,  you cannot delete that Note. 

I think when create a note, you can use this `dispatch(setCaseId(res.caseIdentifier));` to update the caseId in the redux store. 

And I just realized some of my codes [here](https://github.com/bcgov/nr-compliance-enforcement/pull/329/files#diff-8f66c21cca11dfdeec23a85d4fb894b0cc0c2a33567f39edd8ae9c79741084c0) are lost in the split-case-reducer refactor :(

2024-04-17 01:09 UTC, marqueone-ps commented
@Scarlett-Truong I'm not sure I follow what you mean. When I was testing I was making sure to test when there wasn't any other outcome type so I never ran into a problem deleting. I'm not sure that dispatching the caseId makes sense becasue when I create/update/delete a note one of the things I do is reload the casefile to make sure that the changes get applied. Can you show me what you mean tomorrow?

2024-04-17 01:15 UTC, marqueone-ps commented
@Scarlett-Truong I see what you mean now. I've updated the notes to reflect that change.

2024-04-17 01:59 UTC, Scarlett-Truong commented
> @Scarlett-Truong I see what you mean now. I've updated the notes to reflect that change.

Have you pushed the update @marqueone-ps ? Cuz I haven't seen any changes 😅

2024-04-22 21:33 UTC, afwilcox commented on frontend/src/app/components/containers/complaints/outcomes/supplemental-notes/supplemental-notes-item.tsx
> -            id="notes-edit-button"
Removing the notes-edit-button id from the Edit button is causing some of the Cypress tests to be skipped as the edit button can't be found.

2024-04-22 22:04 UTC, Scarlett-Truong commented
Besides the sonar cloud fail at cypress test, everything looks good to me.

2024-04-22 22:53 UTC, Scarlett-Truong approved these changes

2024-04-22 23:00 UTC, afwilcox approved these changes

2024-04-22 23:01 UTC, merged