bug: CE-553 Resolve the issue of GUID in the officer field
bcgov/nr-compliance-enforcement pull request #373
Opened 2024-04-24 21:24 UTC by dmitri-korin-bcps

# Description

The cause of the issue described in CE-553 is when a user refreshes the complaint details the data (officer list) that is supposed to be in Redux state is missing. It only occurs in the test environment. Debugging found the the app attempts to run setOfficers action but it happens late in a sequence when complaint detail component is already rendered.  

The code is modified to retrieve the Redux state in the Assessment and Prevention and Eductions sections in the same way as it was done in other sections. Also the list of officers is added to a dependency array of useEffect that refresh the view. It should re-render Complaint Details component when officer list is populated.

Fixes # (CE-553)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Add an Assessment to a complaint. Refresh the page. Observe that officer name is translated correctly

## Checklist

- [x] New and existing unit tests pass locally with my changes

2024-04-24 21:55 UTC, marqueone-ps requested changes
There's a couple changes here you're going to want to address, but otherwise looks good @dmitri-korin-bcps

2024-04-24 21:55 UTC, marqueone-ps commented on frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
> +  const { officers } = useAppSelector((state) => state.officers);
this doesn't appear to be used by anything, and should be removed

2024-04-24 21:55 UTC, marqueone-ps commented on frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
> +  }, [complaintData, officers]);
this dependancy array should include all of the objects you're using in the useEffect, but again the officers object din't being used here and is redundant. 


```
//-- suggested dependancy array

useEffect(() => {
  //-- existing code
  // eslint-disable-next-line react-hooks/exhaustive-deps
}, [assignableOfficers, complaintData, personGuid]);

2024-04-24 21:55 UTC, marqueone-ps commented on frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
same concern as with the hwcr-complaint-assessment component, officers doesn't appear to be used

2024-04-24 21:55 UTC, marqueone-ps commented on frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
> +  }, [complaintData, officers]);
the same suggestion as the hwcr-complaint-assesment component, remove the officers object from the dependancy array and include the objects that should be there

2024-04-24 23:04 UTC, marqueone-ps approved these changes

2024-04-25 16:24 UTC, afwilcox approved these changes

2024-04-25 16:24 UTC, merged